name = "LocalRegistry"
uuid = "89398ba2-070a-4b16-a995-9893c55d93cf"
authors = ["Gunnar Farneb√§ck <gunnar@lysator.liu.se>"]
version = "0.3.0"

[deps]
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
RegistryTools = "d1eb7eb1-105f-429d-abf5-b0f65cb9e2c4"
UUIDs = "cf7118a7-6976-5b1a-9a39-7adc72f591a4"

[compat]
RegistryTools = "1.4"
julia = "1.1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
