name = "LocalRegistry"
uuid = "89398ba2-070a-4b16-a995-9893c55d93cf"
authors = ["Gunnar Farneb√§ck <gunnar@lysator.liu.se>"]
version = "0.6.0"

[deps]
Git = "d7ba0133-e1db-5d97-8f8c-041e4b3a1eb2"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
RegistryInstances = "2792f1a3-b283-48e8-9a74-f99dce5104f3"
RegistryTools = "d1eb7eb1-105f-429d-abf5-b0f65cb9e2c4"
TOML = "fa267f1f-6049-4f14-aa54-33bafae1ed76"
UUIDs = "cf7118a7-6976-5b1a-9a39-7adc72f591a4"

[compat]
CodecZlib = "0.5, 0.6, 0.7"
Git = "1.3"
RegistryInstances = "0.1"
RegistryTools = "2.2"
julia = "1.6"

[extras]
CodecZlib = "944b1d66-785c-5afd-91f1-9de20f533193"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["CodecZlib", "Pkg", "Test"]
